--- #YAML:1.0
name:               Catalyst-Plugin-Captcha
version:            0.04
abstract:           create and validate Captcha for Catalyst
author:
    - Masahiro Nagano <kazeburo@nomadscafe.jp>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:             5.3
    Catalyst::Plugin::Session:  0
    GD::SecurityImage:    0
    HTTP::Date:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
